# Generated by Django 3.1.4 on 2021-01-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='autor',
            new_name='author',
        ),
    ]
