# Generated by Django 3.1.4 on 2021-01-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_read_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='read_num',
            new_name='readed_num',
        ),
    ]
