# Generated by Django 3.1.4 on 2021-01-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210114_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
